brew "stow"
brew "starship"
brew "yq"
brew "jq"
brew "docker"
brew "anyenv"
brew "yarn"
brew "watch"
brew "mas"
brew "mysql"
brew "postgresql"
brew "kustomize"
brew "grpcurl"
brew "protobuf"
brew "awscli"

cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "sourcetree"
cask "sequel-pro"
cask "clipy"
cask "docker"
cask "appcleaner"
cask "google-cloud-sdk"
cask "android-studio"
cask "adoptopenjdk"
cask "unity-hub"
cask "blender"
cask "autodesk-fusion360"
cask "appcleaner"
cask "dbeaver-community"
cask "zoom"
cask "kindle"
cask "steam"
cask "background-music"

mas "Xcode", id: 497799835
mas "line", id: 539883307
