brew "stow"
brew "starship"
brew "yq"
brew "jq"
brew "docker"
brew "anyenv"
brew "yarn"
brew "watch"

cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "sourcetree"
cask "sequel-pro"
cask "clipy"
cask "docker"
cask "appcleaner"
cask "google-cloud-sdk"
