#!/bin/sh

set -e

GIT_CLONE_PATH=~/projects/github.com/nekoshita
STOW_PACKAGES=$GIT_CLONE_PATH/dotfiles/packages

echo 'Change default shell to zsh'
if [ "$(dscl . -read ~/ UserShell)" = "UserShell: /bin/bash" ]; then 
    chsh -s /bin/zsh
    chmod -R 755 /usr/local/share/zsh
    chown -R root:staff zsh
fi 


echo 'Setup Homebrew'
if [ ! -f /usr/local/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi


echo 'Clone dotfiles'
if [ ! -d "$GIT_CLONE_PATH" ]; then
    mkdir -p "$GIT_CLONE_PATH"
fi

if [ ! -d "$GIT_CLONE_PATH"/dotfiles ]; then
    cd "$GIT_CLONE_PATH"
    git clone https://github.com/nekoshita/dotfiles
fi


echo 'Setup apps and CLIs'
brew bundle -v --file "$GIT_CLONE_PATH"/dotfiles/Brewfile


echo 'Setup config files'
if [ ! -d ~/.config ]; then
	mkdir ~/.config
fi

if [ ! -d ~/.config/starship ]; then
    mkdir ~/.config/starship
fi


stow -v -d "$STOW_PACKAGES_PATH" -t ~ $(ls -m "$STOW_PACKAGES_PATH" | tr ',' ' ')

